# Generated by Django 4.2.13 on 2024-06-10 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userissue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='developer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'developer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developer_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='product_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'product_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='project_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='issue',
            name='quality_assurance',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'quality_assurance'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='reporter',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='issue_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='issues.issue'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userissue',
            unique_together={('user', 'issue', 'role')},
        ),
    ]
