# Generated by Django 4.2.13 on 2024-06-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='issue_id',
            new_name='issue',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
