# Generated by Django 4.2.13 on 2024-07-05 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userissue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
