# Generated by Django 4.2.13 on 2024-07-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_userissue_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='severity',
            field=models.IntegerField(choices=[('1', '1 - Critical'), ('2', '2 - High'), ('3', '3 - Medium'), ('4', '4 - Low')], default=4),
        ),
    ]
