# Generated by Django 4.2.13 on 2024-06-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_changed', models.CharField(choices=[('title', 'Title'), ('description', 'Description'), ('severity', 'Severity'), ('project_title', 'Project Title'), ('type', 'Type'), ('status', 'Status'), ('developer', 'Developer'), ('quality_assurance', 'Quality Assurance'), ('product_manager', 'Product Manager')], max_length=50)),
                ('old_value', models.CharField(max_length=255)),
                ('new_value', models.CharField(max_length=255)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.issue')),
            ],
        ),
    ]
