# Generated by Django 4.2.13 on 2024-06-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='field_changed',
            field=models.CharField(choices=[('title', 'Title'), ('description', 'Description'), ('severity', 'Severity'), ('project', 'Project'), ('type', 'Type'), ('status', 'Status'), ('developer', 'Developer'), ('quality_assurance', 'Quality Assurance'), ('product_manager', 'Product Manager')], max_length=50),
        ),
    ]
