# Generated by Django 4.2.13 on 2024-06-10 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0003_alter_comment_issue_id_alter_comment_user_id_and_more'),
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='change_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='change',
            name='field_changed',
            field=models.CharField(choices=[('title', 'Title'), ('description', 'Description'), ('severity', 'Severity'), ('project_title', 'Project Title'), ('type', 'Type'), ('status', 'Status'), ('developer', 'Developer'), ('quality_assurance', 'Quality Assurance'), ('product_manager', 'Product Manager')], max_length=50),
        ),
        migrations.AlterField(
            model_name='change',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.issue'),
        ),
        migrations.AlterField(
            model_name='change',
            name='new_value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='change',
            name='old_value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='change',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
