# Generated by Django 4.2.13 on 2024-07-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_change_field_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='new_value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='change',
            name='old_value',
            field=models.TextField(),
        ),
    ]
